version: '3.8'

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: his-dozzle
    ports:
      - '${DOZZLE_PORT:-8080}:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - his_sik_network
